# We use the secret file to define secret enviromental variables and there values
# we shouldnt define the Database username and passwd in a plain text in the deployment file of mongodb 
apiVersion: v1
kind: Secret
metadata:
        name: mongodb-secret
type: Opaque
data:
        mongo-root-username: dXNlcm5hbWU=
        mongo-root-passwd: cGFzc3dk
